"""
frigate_bot configuration.
Copy to config.py and fill in:  cp config.example.py config.py
"""

# --- DELIVERY CHANNELS ---
# Available: TG_BOT (Telegram Bot API), TG_MTPROTO (Telegram user account, videos up to 2 GB)
# Uncomment the one you need; the config block of a channel you do not use can be deleted
ENABLED_CHANNELS = ['TG_BOT']
# ENABLED_CHANNELS = ['TG_MTPROTO']
# ENABLED_CHANNELS = ['TG_BOT', 'TG_MTPROTO']

# --- TG_BOT: Telegram Bot API ---
# Token from @BotFather
TG_BOT_CONFIG = {
    "token": "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11",
    "chat_id": -1234567890
}

# --- TG_MTPROTO: Telegram user account (Telethon) ---
# api_id and api_hash from https://my.telegram.org/apps
TG_MTPROTO_CONFIG = {
    "api_id": 123456,
    "api_hash": 'abcdef1234567890abcdef1234567890',
    "session_name": 'frigate_session',
    "chat_id": -1234567890
}

# Public URL of your Frigate UI, e.g. "http://192.168.1.10:5000" or "https://frigate.example.com".
# Adds a review link at the bottom of every message; "" — no link.
FRIGATE_PUBLIC_URL = ""

# Object labels in the caption: 'en' / 'ru' — emoji + name (see pretty_labels.py);
# None — raw Frigate labels (person, car)
PRETTY_LABELS = 'en'

# AI summary from Frigate's review.genai (generated by Frigate, see README)
GENAI_REVIEW_SHOW = True        # add the summary to the caption
GENAI_REVIEW_WAIT = 60          # how long to wait for it, seconds from the start of processing
GENAI_REVIEW_POLL = 5.0         # poll interval, seconds

# Video clip
CLIP_START_SHIFT = 5          # padding before the event, seconds
CLIP_END_SHIFT = 5            # padding after the event, seconds
CLIP_MAX_LEN = 180            # maximum clip length, seconds (fits the Bot API limit with default encoding)

# Encoding
OUTPUT_WIDTH = 1024
OUTPUT_FPS = 25
OUTPUT_QP = 26

# Logging
LOG_LEVEL = 'INFO'      # console (docker logs) level; frigate_bot.log always has everything
